export const REQUEST_PROGRESS_BAR_DATA = 'REQUEST_PROGRESS_BAR_DATA';
export const RECEIVE_PROGRESS_BAR_DATA = 'RECEIVE_PROGRESS_BAR_DATA';
export const RECEIVE_PROGRESS_BAR_ERROR = 'RECEIVE_PROGRESS_BAR_ERROR';

export const REQUEST_API_ACCESS_DATA = 'REQUEST_API_ACCESS_DATA';
export const RECEIVE_API_ACCESS_DATA = 'RECEIVE_API_ACCESS_DATA';
export const RECEIVE_API_ACCESS_ERROR = 'RECEIVE_API_ACCESS_ERROR';

export const REQUEST_HERO_DATA = 'REQUEST_HERO_DATA';
export const RECEIVE_HERO_DATA = 'RECEIVE_HERO_DATA';
export const RECEIVE_HERO_ERROR = 'RECEIVE_HERO_ERROR';

export const REQUEST_GRID_DATA = 'REQUEST_GRID_DATA';
export const RECEIVE_GRID_DATA = 'RECEIVE_GRID_DATA';
export const RECEIVE_GRID_ERROR = 'RECEIVE_GRID_ERROR';

export const REQUEST_CATEGORIES_DATA = 'REQUEST_CATEGORIES_DATA';
export const RECEIVE_CATEGORIES_DATA = 'RECEIVE_CATEGORIES_DATA';
export const RECEIVE_CATEGORIES_ERROR = 'RECEIVE_CATEGORIES_ERROR';

export const REQUEST_SEARCH_NAV_DATA = 'REQUEST_SEARCH_NAV_DATA';
export const RECEIVE_SEARCH_NAV_DATA = 'RECEIVE_SEARCH_NAV_DATA';
export const RECEIVE_SEARCH_NAV_ERROR = 'RECEIVE_SEARCH_NAV_ERROR';

export const REQUEST_SEARCH_CHANNELS_DATA = 'REQUEST_SEARCH_CHANNELS_DATA';
export const RECEIVE_SEARCH_CHANNELS_DATA = 'RECEIVE_SEARCH_CHANNELS_DATA';
export const RECEIVE_SEARCH_CHANNELS_ERROR = 'RECEIVE_SEARCH_CHANNELS_ERROR';

export const REQUEST_SEARCH_VIDEOS_DATA = 'REQUEST_SEARCH_VIDEOS_DATA';
export const RECEIVE_SEARCH_VIDEOS_DATA = 'RECEIVE_SEARCH_VIDEOS_DATA';
export const RECEIVE_SEARCH_VIDEOS_ERROR = 'RECEIVE_SEARCH_VIDEOS_ERROR';

export const REQUEST_SEARCH_RESET_DATA = 'REQUEST_SEARCH_RESET_DATA';
export const RECEIVE_SEARCH_RESET_DATA = 'RECEIVE_SEARCH_RESET_DATA';
export const RECEIVE_SEARCH_RESET_ERROR = 'RECEIVE_SEARCH_RESET_ERROR';

export const REQUEST_PROFILE_DATA = 'REQUEST_PROFILE_DATA';
export const RECEIVE_PROFILE_DATA = 'RECEIVE_PROFILE_DATA';
export const RECEIVE_PROFILE_ERROR = 'RECEIVE_PROFILE_ERROR';

export const REQUEST_HOME_RAIL_CHANNELS_DATA = 'REQUEST_HOME_RAIL_CHANNELS_DATA';
export const RECEIVE_HOME_RAIL_CHANNELS_DATA = 'RECEIVE_HOME_RAIL_CHANNELS_DATA';
export const RECEIVE_HOME_RAIL_CHANNELS_ERROR = 'RECEIVE_HOME_RAIL_CHANNELS_ERROR';

export const REQUEST_HOME_RAIL_PLAYLISTS = 'REQUEST_HOME_RAIL_PLAYLISTS';
export const RECEIVE_HOME_RAIL_PLAYLIST_DATA = 'RECEIVE_HOME_RAIL_PLAYLIST_DATA';
export const RECEIVE_HOME_RAIL_PLAYLIST_ERROR = 'RECEIVE_HOME_RAIL_PLAYLIST_ERROR';

export const REQUEST_IVP_RAIL_CHANNELS_DATA = 'REQUEST_IVP_RAIL_CHANNELS_DATA';
export const RECEIVE_IVP_RAIL_CHANNELS_DATA = 'RECEIVE_IVP_RAIL_CHANNELS_DATA';
export const RECEIVE_IVP_RAIL_CHANNELS_ERROR = 'RECEIVE_IVP_RAIL_CHANNELS_ERROR';

export const REQUEST_IVP_VIDEO = 'REQUEST_IVP_VIDEO';
export const RECEIVE_IVP_VIDEO = 'RECEIVE_IVP_VIDEO';
export const RECEIVE_IVP_VIDEO_ERROR = 'RECEIVE_IVP_VIDEO_ERROR';
export const REQUEST_CLEAN_IVP = 'REQUEST_CLEAN_IVP';
export const RECEIVE_CLEAN_IVP = 'RECEIVE_CLEAN_IVP';

export const REQUEST_MORE_LIKE_THIS_DATA = 'REQUEST_MORE_LIKE_THIS_DATA';
export const RECEIVE_MORE_LIKE_THIS_DATA = 'RECEIVE_MORE_LIKE_THIS_DATA';
export const RECEIVE_MORE_LIKE_THIS_ERROR = 'RECEIVE_MORE_LIKE_THIS_ERROR';

export const REQUEST_RESUMPTION_DATA_SEND = 'REQUEST_RESUMPTION_DATA_SEND';
export const RECEIVE_RESUMPTION_DATA_SEND = 'RECEIVE_RESUMPTION_DATA_SEND';
export const RECEIVE_RESUMPTION_DATA_SEND_ERROR = 'RECEIVE_RESUMPTION_DATA_SEND_ERROR';

export const REQUEST_POINTS_DATA = 'REQUEST_POINTS_DATA';
export const RECEIVE_POINTS_DATA = 'RECEIVE_POINTS_DATA';
export const RECEIVE_POINTS_ERROR = 'RECEIVE_POINTS_ERROR';
