version: 0.0
os: linux
files:
  - source: ./
    destination: /var/www/releases/nosey.com
hooks:
  ApplicationStop:
    - location: scripts/deregister_from_elb.sh
      runas: root
    - location: scripts/app-stop.sh
      runas: nosey.com
  AfterInstall:
    - location: scripts/app-stop.sh
      runas: nosey.com
    - location: scripts/after-install.sh
      runas: root
      timeout: 600
  ApplicationStart:
    - location: scripts/app-start.sh
      timeout: 600
      runas: nosey.com
    - location: scripts/register_with_elb.sh
      runas: root
